
package com.mycompany.bounceball;

import java.awt.Color;

/**
 *
 * @author ISO53
 */
public class BounceBall extends javax.swing.JFrame {

    /**
     * Creates new form BounceBall
     */
    Slab rightSlab;
    Ball gameBall;

    public BounceBall() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        pnl_background = new javax.swing.JPanel();
        pnl_tools = new javax.swing.JPanel();
        btn_start = new javax.swing.JButton();
        lbl_score = new javax.swing.JLabel();
        lbl_speed = new javax.swing.JLabel();
        lbl_game = new javax.swing.JLabel();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bounce Ball");

        pnl_background.setBackground(new java.awt.Color(51, 51, 51));
        pnl_background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnl_backgroundMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout pnl_backgroundLayout = new javax.swing.GroupLayout(pnl_background);
        pnl_background.setLayout(pnl_backgroundLayout);
        pnl_backgroundLayout.setHorizontalGroup(
            pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl_backgroundLayout.setVerticalGroup(
            pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        pnl_tools.setBackground(new java.awt.Color(51, 51, 51));

        btn_start.setText("START THE GAME");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        lbl_score.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lbl_score.setForeground(new java.awt.Color(255, 255, 255));
        lbl_score.setText("SCORE: 0");
        lbl_score.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lbl_scorePropertyChange(evt);
            }
        });

        lbl_speed.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lbl_speed.setForeground(new java.awt.Color(255, 255, 255));
        lbl_speed.setText("SPEED: ");

        lbl_game.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_game.setForeground(new java.awt.Color(204, 0, 0));
        lbl_game.setText("                                     ");

        javax.swing.GroupLayout pnl_toolsLayout = new javax.swing.GroupLayout(pnl_tools);
        pnl_tools.setLayout(pnl_toolsLayout);
        pnl_toolsLayout.setHorizontalGroup(
            pnl_toolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_toolsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_start)
                .addGap(18, 18, 18)
                .addComponent(lbl_score, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(lbl_speed, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                .addComponent(lbl_game)
                .addContainerGap())
        );
        pnl_toolsLayout.setVerticalGroup(
            pnl_toolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_toolsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_toolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_toolsLayout.createSequentialGroup()
                        .addGroup(pnl_toolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_score)
                            .addComponent(lbl_speed)
                            .addComponent(btn_start))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_game, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_tools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnl_tools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed

        btn_start.setEnabled(false);

        Slab leftSlab = new Slab(Color.BLUE);
        leftSlab.setSize(50, 100);
        leftSlab.setLocation(25, 320);

        rightSlab = new Slab(Color.RED);
        rightSlab.setSize(50, 100);
        rightSlab.setLocation(pnl_background.getWidth() - 45, 25);

        gameBall = new Ball();
        gameBall.setSize(25, 25);
        gameBall.setLocation(200, 200);

        pnl_background.add(leftSlab);
        pnl_background.add(rightSlab);
        pnl_background.add(gameBall);
        
        gameBall.start();
        
        lbl_game.setForeground(Color.GREEN);
        lbl_game.setText("G A M E   S T A R T E D");

        pnl_background.repaint();
    }//GEN-LAST:event_btn_startActionPerformed

    private void pnl_backgroundMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_backgroundMouseMoved

        if (rightSlab != null) {
            rightSlab.setLocation(rightSlab.getLocation().x, evt.getY() - 25);

            if (rightSlab.getLocation().y < 0) {
                rightSlab.setLocation(rightSlab.getLocation().x, 1);
            }

            if (rightSlab.getLocation().y > 345) {
                rightSlab.setLocation(rightSlab.getLocation().x, 344);
            }
        }
    }//GEN-LAST:event_pnl_backgroundMouseMoved

    private void lbl_scorePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lbl_scorePropertyChange
        // TODO add your handling code here:
        int score = Integer.parseInt(lbl_score.getText().substring(7));
        
        if(gameBall != null && score % 5 == 0) {
            gameBall.setDelay(gameBall.getDelay() - gameBall.getDelay() / 5);
        }
    }//GEN-LAST:event_lbl_scorePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BounceBall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BounceBall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BounceBall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BounceBall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BounceBall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_start;
    public static javax.swing.JLabel lbl_game;
    public static javax.swing.JLabel lbl_score;
    public static javax.swing.JLabel lbl_speed;
    private java.awt.Panel panel1;
    private javax.swing.JPanel pnl_background;
    private javax.swing.JPanel pnl_tools;
    // End of variables declaration//GEN-END:variables
}
